#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 -Targe

#---------------------------------#
# Tests
#---------------------------------#
test: off

#---------------------------------#
#  Pull Requests                  #
#---------------------------------#
pull_requests:
  do_not_increment_build_number: true

#---------------------------------#
#  General                        #
#---------------------------------#
skip_branch_with_pr: true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - master

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- tools -> recipe.cake, tools/packages.config

#---------------------------------#
#  Skip builds for doc changes    #
#---------------------------------#
skip_commits:
  # Regex for matching commit message
  message: /\(doc\).*/
